name: Check

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install Rust toolchain
        run: rustup show active-toolchain || rustup toolchain install

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: make dogfood
        run: make dogfood && git diff --exit-code

      - name: make lint
        run: make lint

      - name: make test
        run: make test

  old-rust:
    name: Test on old Rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install Rust toolchain
        run: rustup show active-toolchain || rustup toolchain install

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: make test-old
        run: make test-old
